# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=folk.sisby
user=sisby-folk
slug=crunchy-crunchy-advancements
modId=crunchy_crunchy_advancements
modName=Crunchy Crunchy Advancements
modDescription=Takes a configurable and compatible bite out of advancements.
authors=Sisby folk
license=LGPL-3.0-or-later
# Mod Version
baseVersion=1.6.3
# Branch Metadata
branch=1.18
compatibleVersions=1.17, 1.17.1, 1.18, 1.18.1, 1.18.2
compatibleLoaders=fabric, quilt
